name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Cypress Reports
        uses: actions/upload-artifact@v4
        if: always() # if test case is fail it will still show report in cypress reports 
        with:
            name: mochaAwesome-HTML
            path: cypress/reports/html # or path/to/artifact
        
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_MESSAGE: 'Test Automation Report https://github.com/Anshita-Bhasin/Cypress-E2E/actions/runs/${{github.run_id}}'
            SLACK_TITLE: Cypress Web Test
            SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK }}