name: Parallel Integration 
on: push
jobs:
  Add-To-Cart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test-add-to-Cart
      - uses: actions/upload-artifact@v4
        with:
            name: mochaAwesome-HTML-AddToCart
            path: cypress/reports/html # or path/to/artifact

  Reg-Page-run:
        runs-on: ubuntu-22.04
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        # Install npm dependencies, cache them correctly
        # and run all Cypress tests
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            command: npm run test-reg-Page
        - uses: actions/upload-artifact@v4
          with:
            name: mochaAwesome-HTML-Registration
            path: cypress/reports/html # or path/to/artifact